Moves the mouse to the corner before taking a screenshot.
aeon0/botty pull request #102
Opened 2021-11-24 07:58 UTC by bjoerm

Prevents thus mouse from covering loot.

Here an example where this might have happened (ring got not picked up).
![not picked up ring - info_debug_drop_20211122_203831](https://user-images.githubusercontent.com/8392548/143197636-e8f0ef22-690a-400b-bf18-f01bc90c6992.png)

2021-11-24 11:22 UTC, aeon0 requested changes
Functionality is useful. But I dont like it in the screen grabbing. Maybe add a function to custom_mouse.py e.g. `mouse.hide()`. In the hide function it would be cool if it randomly moves it to any of the 4 corners with a bit of a randomized area.

2021-11-24 11:22 UTC, aeon0 commented on src/screen.py
> +            mouse.move(0, 0)  # Moving the mouse to the edge of the screen to not cover any loot.
You will have to convert 0, 0 to monitor coordinates. If someone is running a two monitor setup the (0, 0) screen coordinate might be at (1920, 0) for example.

2021-11-24 11:33 UTC, bjoerm commented
Thanks for the feedback. Will think about it.

2021-12-07 15:42 UTC, bjoerm commented
Didn't have time recently to work on this. Shall this be closed for now, @aeon0?

2021-12-15 07:45 UTC, aeon0 commented
Stale PR

2021-12-15 07:45 UTC, closed without merging