Telekinesis for pots/gold if set
aeon0/botty pull request #108
Opened 2021-11-24 21:21 UTC by mgleed

Tested about 10 runs with sorc, seems to work well. I don't have hammerdin to ensure that there's no issue, but I don't think there'd be any problem.

Will plan to revisit WP and stash telekinesis later, but this should be good-to-go. Ty for the pointers.

2021-11-24 22:25 UTC, aeon0 requested changes
Good job!
My only question is, does telek. have a range? So could it happen that it is out of range and it will just cast telek. forever??

2021-11-24 22:25 UTC, aeon0 commented on src/char/sorceress.py
> +        if self._skill_hotkeys["telekinesis"] and any(x in item_name for x in ['potion', 'misc_gold']):
nice syntax! : )

2021-11-24 22:25 UTC, aeon0 commented on src/char/sorceress.py
> +            wait(0.35,0.45)
utilize `self._cast_duration` here

2021-11-24 22:25 UTC, aeon0 commented on src/char/sorceress.py
> +            super().pick_up_item((pos[0], pos[1]),item_name)
`(pos[0], pos[1])` is the same as `pos`, no?

2021-11-24 23:05 UTC, mgleed commented
> Good job! My only question is, does telek. have a range? So could it happen that it is out of range and it will just cast telek. forever??

I can work on these changes in a couple hours. The pickup item function only occurs if the item is within a certain distance,  otherwise char.move is called as you've written in pickit.py so range shouldn't be an issue.

2021-11-25 02:13 UTC, mgleed commented
I've implemented the changes you asked @aeon0 . I'm not really sure the cast_duration change was necessary since the time it takes to check all templates is so long. If you agree, I can rewind a commit and just fix the `pos` thing. The delay at the end of the pick is to ensure the item name is off the screen before doing another screen capture.

2021-11-25 02:19 UTC, mgleed commented
Overall I don't know if performance improves meaningfully with this implementation of telekinesis, but I think it's cool ;). The ideal would be to integrate item_dist; i.e., if the item is at mid-range then use telekinesis, close proximity left click, and far range tele and left click.

2021-11-25 13:38 UTC, aeon0 requested changes
Did you do a test run? I am not sure why you dont want to the cast duration from i_char which is determined by the parameters (casting_frames). Telek. should be effected by it.

I will also test this, but looks good so far.

2021-11-25 13:38 UTC, aeon0 commented on src/pickit.py
> +                    prev_cast_start = char.pick_up_item((x_m, y_m),item_name=closest_item.name,prev_cast_start=prev_cast_start)
You really dont like whitespaces, do you? :D Please add them after `, `

2021-11-25 16:06 UTC, mgleed commented
> Did you do a test run? I am not sure why you dont want to the cast duration from i_char which is determined by the parameters (casting_frames). Telek. should be effected by it.
> 
> I will also test this, but looks good so far.

I included self._cast_duration in that commit for completeness sake, but nested in a conditional block. Due to pickit time it's pretty much inevitable that the delay between picks is greater than cast duration.

2021-11-25 17:24 UTC, aeon0 commented on src/char/sorceress.py
> +            cast_duration_wait = (self._cast_duration - interval)
you do use self._cast_duration, sry ^^

2021-11-25 19:38 UTC, mgleed commented
Fixed the white whitespace,let me know if there's anything else,thank you

2021-11-26 18:36 UTC, aeon0 commented on src/char/sorceress.py
> +            super().pick_up_item(pos)
return here and pass through params
```suggestion
            return super().pick_up_item(pos, item_name, prev_cast_start)
```

2021-11-26 19:41 UTC, merged