implement saved_games_folder param
aeon0/botty pull request #179
Opened 2021-12-02 19:29 UTC by cesarvargas00

This helps me whenever I have to re-run the auto-settings, since my default folder is different than the one that this bot uses:

`C:\Users\cesar\Saved Games\Diablo II Resurrected` -> my saved games folder

`C:\\Users\\cesar-local\\Saved Games\\Diablo II Resurrected` -> botty's default saved games folder

`os.getlogin()` differs from my user folder. I'm not sure why this happens, so I came up with this implementation under the **[general]** settings in `params.ini`.

2021-12-02 22:36 UTC, aeon0 requested changes
Thx for the PR. Looks good. Only thing missing would be a short documentation in the readme.md.

2021-12-02 23:55 UTC, cesarvargas00 commented
> Thx for the PR. Looks good. Only thing missing would be a short documentation in the readme.md.

Doing it right now!

2021-12-02 23:58 UTC, cesarvargas00 commented
done

2021-12-03 05:59 UTC, aeon0 approved these changes

2021-12-03 05:59 UTC, merged