Adding variables to give users a way to set a custom hork time
aeon0/botty pull request #298
Opened 2021-12-16 23:14 UTC by Jizanator

Horking time will vary on the user. Each boss will have their own hork timer.

2021-12-17 02:23 UTC, Jizanator commented
Should be added on line12 of barbarian.py

2021-12-17 02:53 UTC, nekolr commented
include your own configurations?

2021-12-17 03:07 UTC, Jizanator commented
Sorry new to this. What does that mean? I changed 3 files one of them being the new param to include the new vars.

2021-12-17 03:26 UTC, nekolr commented
> Sorry new to this. What does that mean? I changed 3 files one of them being the new param to include the new vars.

you can add your own configuration into the `custom.ini`

2021-12-29 15:43 UTC, egut125 requested changes

2021-12-29 15:43 UTC, egut125 commented on config/params.ini
> +custom_message_hook=https://discord.com/api/webhooks/908525387724767322/eFuC_GX6wNmbhQxuOi5VSywTs185MKXPI8TS5QNvqmzTUsNIdxzJsqPcGvk9N2oGFTYj
Don't include your personal changes to params.ini. These are defaults that should not be touched unless there is strong reason. To set your own when using Botty create a custom.ini in the same folder and overwrite you values there. 

Only include your new fields or necessary default changes.

2021-12-29 15:43 UTC, egut125 commented on config/params.ini
> +hork_time_nihlatak=6.0
Undo all changes in this file besides these hork_time ones

2021-12-29 15:43 UTC, egut125 commented on src/char/barbarian.py
> -        # keyboard.send(self._char_config["weapon_switch"])
These pre buff weapon switch probably shouldn't have changed with this pr. These are unrelated to hork time setting below. Remove them from this pr.

2021-12-29 15:43 UTC, egut125 commented on src/char/barbarian.py.bak
> +import keyboard
Don't commit .bak files they're unnecessary to keep in the GitHub repo.

2022-01-31 22:06 UTC, mgleed commented
Closing due to lack of activity, feel free to merge master and will revisit if needed

2022-01-31 22:06 UTC, closed without merging