Adding Clearing Trash in Chaos Sanctuary & moving attack functions to classes
aeon0/botty pull request #457
Opened 2022-01-17 13:28 UTC by jobithu

params.ini cs_clear_trash=1 now working.
To allow further classes to be built-in, diablo.py functions for attacking mobs are moved to the char.py for:
- all sorcs
- hammerdin
- trapsin
- necro (added lower resist & poison nova as skills to params.ini)

2022-01-17 13:29 UTC, jobithu commented
still work in progress, no merge required for now.

2022-01-17 14:49 UTC, jobithu commented
script working now, but still several pather got stuck -> more templates needed for the existing nodes 67x & 68x

2022-01-17 15:27 UTC, aeon0 requested changes
Overall this feels like lots of duplicate code :/ 
Also, please try to chop this PR up in smaller pieces. This is too much at once, impossible to review. E.g. 
1) Refactor code to a point that you can add the clear trash. (such as add pickit to ichar)
2) Implement it for Hdin
3) Separate PRs for other classes
4) Robustify pathing

2022-01-17 15:27 UTC, aeon0 commented on src/char/i_char.py
> +    def __init__(self, skill_hotkeys: Dict, char_config: Dict, screen: Screen, template_finder: TemplateFinder, ui_manager: UiManager):
Dont add char_config back in please. It is taken for the config static class

2022-01-18 07:49 UTC, jobithu commented
closing PR, will open multiple new ones as discussed & revert majority of pathing instructions back to diablo.py

2022-01-18 07:49 UTC, closed without merging