Fixed CTA order - battle command needs to be before battle orders. Added several new assets for white/gray bows, swords and grandfather.
aeon0/botty pull request #480
Opened 2022-01-25 15:15 UTC by ggodev

2022-01-25 19:12 UTC, pokzcodes commented
This seems like a good change, but it looks like you included some other changes/files that are not related to this one. I would bet that aeon will want you to split those changes out from the CTA change.

2022-01-26 00:05 UTC, ggodev commented
> This seems like a good change, but it looks like you included some other changes/files that are not related to this one. I would bet that aeon will want you to split those changes out from the CTA change.

Neither of the changes changes the already existing logic, but I could split them up if needed.

2022-01-28 18:36 UTC, VladimirMakaev commented
I think swapping keybinds around doesn't make much sense. Instead I'd suggest to make sure that bot is doing the right sequence. And think it does. E.g. It get's Battle Command first to get +1 and then Battle Orders to benefit from Battle Command that he casted before. 

So I'd remove CTA portion from here and rename PR to reflect the other changes. That's my 2 cents

2022-01-28 18:57 UTC, ggodev commented
> I think swapping keybinds around doesn't make much sense. Instead I'd suggest to make sure that bot is doing the right sequence. And think it does. E.g. It get's Battle Command first to get +1 and then Battle Orders to benefit from Battle Command that he casted before.
> 
> So I'd remove CTA portion from here and rename PR to reflect the other changes. That's my 2 cents

Honestly If the logic is already fixed (which it is), it's best to have the keybindings following that. 
It's a QoL change indeed, but it needs to be there imo.

2022-01-31 23:18 UTC, mgleed requested changes
Happy to merge the item assets if you'd rename the PR. The other change involving the order of BC/BO in the params.ini file is not necessary. Besides, by updating the param.ini file you then reset the defaults of all users who have these keybindings and have not overwritten them in a custom.ini file which may lead to undesired downstream effects.

2022-01-31 23:20 UTC, mgleed commented on config/pickit.ini
please make all of the new items you added have the first field be `=0` by default, users can then change them to 1 if desired.

2022-02-02 01:37 UTC, mgleed commented
No reply for ~48 hours, closing for now. Will reopen depending on interest in revising.

2022-02-02 01:37 UTC, closed without merging