Gbl bugfix
aeon0/botty pull request #583
Opened 2022-02-23 21:15 UTC by RB-Development

bugfix to gambling

2022-02-23 23:03 UTC, Ezro requested changes

2022-02-23 23:03 UTC, Ezro commented on src/ui_components/inventory.py
> -from ui_components.stash import gold_full
from ui_components.stash import set_gold_full

2022-02-23 23:03 UTC, Ezro commented on src/ui_components/inventory.py
> -                            gold_full = True
set_gold_full(True)

2022-02-23 23:43 UTC, Ezro commented
![image](https://user-images.githubusercontent.com/8863899/155429417-d3f302bf-4dd4-4f5c-a5ea-2e74051a2795.png)

2022-02-24 01:42 UTC, mgleed approved these changes
Thank you. Made some small modifications per @Ezro 's recommendations and removed a redundant for loop I found.

2022-02-24 01:59 UTC, merged