Added missing asset for magic monarch & added eth wire fleece
aeon0/botty pull request #70
Opened 2021-11-20 16:53 UTC by bjoerm

2021-11-20 19:40 UTC, aeon0 commented on params.ini
> +eth_armor_wire_fleece=1
Either default this to 0 or add it also for 1280x720 please

2021-11-20 19:40 UTC, aeon0 requested changes
Thx for the updates. Just a little change request please.

2021-11-20 20:03 UTC, bjoerm commented
I changed my PR based on your review input and created another commit for this PR (https://github.com/aeon0/botty/pull/70/commits/70602353de36e06c2fa9895ba8f9d15a3b3e39eb). Is this the correct way or do you need anything else from me?

2021-11-21 15:09 UTC, aeon0 approved these changes

2021-11-21 15:09 UTC, merged

2021-11-21 15:10 UTC, aeon0 commented
> I changed my PR based on your review input and created another commit for this PR ([7060235](https://github.com/aeon0/botty/commit/70602353de36e06c2fa9895ba8f9d15a3b3e39eb)). Is this the correct way or do you need anything else from me?

Nope, that's how I wanted it : ) thx