Transmute All Gems
aeon0/botty pull request #736
Opened 2022-04-26 06:14 UTC by badbrad2889

I added the ability to transmute all gems and select which kind of gems you would like to transmute in the params.ini file

2022-04-26 11:12 UTC, D2RLegit commented
Can't we make it as "transmute gems" as one line instead of having them all seperate in params?

2022-04-26 12:25 UTC, TallenKerl commented
> Can't we make it as "transmute gems" as one line instead of having them all seperate in params?

That's not a good idea because some people keep specific gems for upgrading specific runes or (in my case) rerolling certain items with chips is more effective than with perfect

2022-04-26 12:55 UTC, badbrad2889 commented
@D2RLegit As TallenKerl said I built it this way so the user has the choice which gems they want to keep.

2022-04-26 16:08 UTC, VladimirMakaev requested changes

2022-04-26 16:08 UTC, VladimirMakaev commented on config/params.ini
> +transmute_flawless=1
```suggestion
transmute="chipped,flawed,standard,flawless" ; 
```

2022-04-26 16:09 UTC, VladimirMakaev commented on src/transmute/transmute.py
> +STD_GEMS = [
Please use the word "standard" everywhere since we use full names for all other qualities. So people like me with OCD don't suffer too much :)

2022-04-26 17:05 UTC, badbrad2889 commented
it does it in order the way written already and yes I can change the "STD" to "standard" in the assets and the files if needed

2022-04-26 17:19 UTC, badbrad2889 commented
@VladimirMakaev I reread and now think I understand what you are asking. You want it to be able to pick up all the gems at the same time instead of looping through?

2022-04-26 23:24 UTC, badbrad2889 commented
@VladimirMakaev  im trying to resubmit the required changes. I completely understand what you are asking now so I will work on that for version 2. Thanks for the help and recomendations ;)

2022-04-26 23:47 UTC, badbrad2889 commented on src/transmute/transmute.py
> +STD_GEMS = [
this had been resolved. I see where this could cause issues and even crossed my mind when making originally. Thanks!

2022-04-26 23:48 UTC, badbrad2889 commented on config/params.ini
> +transmute_flawless=1
updated the ini to list style. Thanks

2022-04-27 10:06 UTC, VladimirMakaev requested changes

2022-04-27 10:06 UTC, VladimirMakaev commented on config/params.ini
> +transmute=chipped, flawed, standard, flawless
Leave default as 'flawless' please. As it's not "free" to have a wider option

2022-04-27 13:17 UTC, badbrad2889 commented
I made the requested change Thanks.

2022-04-27 15:14 UTC, VladimirMakaev approved these changes
Can somebody test this before merging?

2022-05-06 04:31 UTC, badbrad2889 commented
@mgleed @VladimirMakaev I made another change and optimize the gem transmute per recommendation. This is to decrease the "cost" and optimize the use of the inventory.

2022-05-06 05:05 UTC, badbrad2889 commented
@mgleed Thank you for running the test again, 
@VladimirMakaev who is able to merge this request?

2022-05-06 05:07 UTC, mgleed commented
If one of the contributors can test this I'd be willing to merge. Not able to get on d2 til sunday to test myself

2022-05-06 05:11 UTC, badbrad2889 commented
@mgleed ok sounds good, I appreciate it!

2022-05-09 08:57 UTC, mgleed commented
I didn't really know any good way to test this so i just threw together a character in hero editor with a bunch of amethysts. This is what happens. @VladimirMakaev @badbrad2889

https://user-images.githubusercontent.com/9866239/167376089-468028ba-cd25-4a4d-bcfb-b10762213794.mp4

2022-05-09 08:59 UTC, mgleed requested changes
Refer to video comment in conversation.

2022-06-07 03:21 UTC, mgleed commented
I had tested this initially but realized the test case I'd contrived was wrong, leading to error. Deleted my video post from earlier. Tested this about three times with a variety of gems and it works nicely.

One way this could be improved is to include logic starting from chipped --> flawless for the number of gems to bring over to be cubed. I.e. if it knows we have 3 flawed gems and 2 normal gems, bring them all over and cube them into each other to make 1 flawless gem. But I don't think that needs to be included in this PR. Nice job @badbrad2889

2022-06-07 03:27 UTC, merged

2022-06-07 19:40 UTC, badbrad2889 commented
@mgleed Thanks for retesting I greatly appreciate it! next implementation I will work on is going to be runes. after I will work on trying to have it grab all the gems at once if you are using that gem and the one above.