Refactor: TemplateFinder()
aeon0/botty pull request #770
Opened 2022-05-14 04:25 UTC by mgleed

Main changes are in template_finder.py, the remaining changes are to modify the codebase accordingly.

Use dataclasses for Template rather than a list

make TemplateFinder into a module of functions, create private function for single match

Use @cache to store all templates in _templates()

Modify dataclass for TemplateMatch to include normalized monitor coordinates as attributes

2022-05-14 05:16 UTC, mgleed commented
Requesting seasoned devs to review. @aeon0 or @VladimirMakaev if you get a chance to review the changes to template_finder.py and give me feedback that'd be appreciated. Thanks!

2022-05-16 17:38 UTC, aeon0 requested changes
Really like it 😍 I wanted to do pretty much exactly that refactoring to be able to use multiprocessing more easily on the template searching.

2022-05-16 17:38 UTC, aeon0 commented on src/template_finder.py
> +    return color_filter(template.img_bgr, color_match)[1], color_filter(img, color_match)[1]
I really like the functional approach taken. But for these two functions that are used once in a pretty obvious if statement, I dont see the benefit.

2022-05-16 19:41 UTC, mgleed commented
> Really like it 😍 I wanted to do pretty much exactly that refactoring to be able to use multiprocessing more easily on the template searching.

Thanks! Any concerns about thread safety?

2022-05-16 21:10 UTC, aeon0 commented
The only thing I am a bit worried about is the cached `_template()` which is not threadsafe. Maybe put a lock around it in `get_template()` and always call that one.

2022-05-17 09:31 UTC, aeon0 approved these changes
Noice!

2022-05-18 05:35 UTC, merged

2022-05-18 05:38 UTC, mgleed commented
Closes #683